## reference: http://docs.travis-ci.com/user/languages/r/

language: r
r:
  - bioc-devel

cache: packages
bioc_required: true

os:
  - linux
  - osx


r_packages:
  - covr
  - ape
  - tidyr
  - tidytree
  - ggtree
  - testthat
  - prettydoc
  - knitr

brew_packages:
  - gcc

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"


after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

